#16. Criar um script que receba 10 números e calcule a média entre eles.
print("Digite um numero:")
n1=float(input())
print("Digite um numero:")
n2=float(input())
print("Digite um numero:")
n3=float(input())
print("Digite um numero:")
n4=float(input())
print("Digite um numero:")
n5=float(input())
print("Digite um numero:")
n6=float(input())
print("Digite um numero:")
n7=float(input())
print("Digite um numero:")
n8=float(input())
print("Digite um numero:")
n9=float(input())
print("Digite um numero:")
n10=float(input())
media=(n1+n2+n3+n4+n5+n6+n7+n8+n9+n10)/10
print(media)