***Variables***
${URL}                             http://www.automationpractice.com/index.php
${BLOUSE_IMAGE}                    xpath=//img[@title="Blouse"]
${BLOUSE_ADD_TO_CARD_BUTTON}       xpath=//a[@data-id-product = 2]
${PROCED_TO_CHECKOUT_BUTTON}       xpath=//a[@title="Proceed to checkout"]
${PROCED_TO_CHECKOUT_BUTTON_2}     xpath=(//span[contains(.,'Proceed to checkout')])[2]
#${STANDART_CHECKOUT_BUTTON} Faltou identificar.
